# spelline — LLM-powered command generator for zsh
# https://github.com/wateret/zsh-spelline
#
# ⚠ DISCLAIMER — USE AT YOUR OWN RISK
#   Commands generated by LLMs can be incorrect, destructive, or dangerous.
#   ALWAYS review a generated command before executing it.
#   The authors accept no liability for any damage caused by commands this
#   plugin produces. You are solely responsible for every command you run.
#
#   Security notice:
#   - This plugin sends shell context (working directory, recent history,
#     tmux scrollback) to an external LLM service. Sensitive data such as
#     tokens, passwords, or internal hostnames visible in your terminal may
#     be included in the request.
#   - The LLM prompt is constructed from untrusted terminal content. A
#     carefully crafted terminal output (e.g. from curl, cat, or a malicious
#     program) could manipulate the prompt to produce harmful commands
#     (prompt injection).
#   - Generated commands are placed into the ZLE buffer, not executed
#     automatically. You must press Enter yourself — but it is still your
#     responsibility to verify the command is safe before doing so.
#
# Requires:
#   An LLM CLI that reads stdin and writes to stdout (default: claude)
#   fzf (optional, for multi-candidate selection)
#   tmux (optional, for terminal context)
#
# Quick start:
#   source spelline.zsh          # or add zsh-spelline to OMZ plugins
#   bindkey '^X^G' _spelline_generate  # if you disabled the default keybinding

# ── dependencies ──────────────────────────────────────────────────────────────
zmodload zsh/datetime 2>/dev/null

# ── config (set before sourcing) ───────────────────────────────────────────────
# Keybindings must be set before sourcing; others can be changed at any time.
: ${ZSH_SPELLINE_KEYBINDING='^G'}          # keybinding (set empty before sourcing to disable)
: ${ZSH_SPELLINE_HISTORY_KEYBINDING='^[g'}  # history search keybinding (Alt+G)

: ${ZSH_SPELLINE_CMD:=""}                   # LLM CLI command (stdin → stdout)
: ${ZSH_SPELLINE_CONTEXT_LINES:=50}        # tmux scrollback lines to send
: ${ZSH_SPELLINE_HISTORY_LINES:=50}        # recent history entries to send
: ${ZSH_SPELLINE_LOG_DIR:=""}              # log directory (empty = no logging)
: ${ZSH_SPELLINE_MAX_CANDIDATES:=10}       # max candidates for multi-option responses
: ${ZSH_SPELLINE_SPINNER:=braille}         # spinner style: braille, ascii
: ${ZSH_SPELLINE_VERBOSE_AFTER:=15}        # seconds before showing cancel hint (0 = never)
: ${ZSH_SPELLINE_SPINNER_COLOR:=animated}  # spinner color: animated, plain, or a color name/number
: ${ZSH_SPELLINE_PROMPT_FUNC:=_spelline_build_prompt}  # custom prompt generator function
: ${ZSH_SPELLINE_HISTORY_FILE:=$HOME/.zsh_spelline_history}  # request history file (empty = no history)

# ── parsing ───────────────────────────────────────────────────────────────────
# Parse LLM output into candidates array.
# Sets global _spelline_candidates=() with parsed results.
_spelline_parse_result() {
  local result="$1"
  _spelline_candidates=()

  [[ -z "$result" ]] && return

  # strip markdown code fences
  result=$(echo "$result" | sed -e '/^```/d')

  # split candidates by '---' delimiter, trim each
  local _candidate=""
  while IFS= read -r _line; do
    if [[ "$_line" == ---* ]] && [[ "${_line//[- ]/}" == "" ]]; then
      _candidate=$(echo "$_candidate" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d')
      [[ -n "$_candidate" ]] && _spelline_candidates+=("$_candidate")
      _candidate=""
    else
      _candidate+="${_candidate:+$'\n'}${_line}"
    fi
  done <<< "$result"
  _candidate=$(echo "$_candidate" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d')
  [[ -n "$_candidate" ]] && _spelline_candidates+=("$_candidate")
}

# ── context helpers ───────────────────────────────────────────────────────────
_spelline_git_info() {
  if git rev-parse --is-inside-work-tree &>/dev/null; then
    local branch=$(git branch --show-current 2>/dev/null)
    local gst=$(git status --short 2>/dev/null | head -5)
    echo "git branch: ${branch}${gst:+\ngit status (short):\n${gst}}"
  fi
}

_spelline_history() {
  fc -l -${ZSH_SPELLINE_HISTORY_LINES} 2>/dev/null \
    | sed 's/^[[:space:]]*[0-9]*[[:space:]]*//' \
    | tail -c $(( ZSH_SPELLINE_HISTORY_LINES * 200 ))
}

_spelline_tmux_context() {
  [[ -z "$TMUX" ]] && return
  tmux capture-pane -p -S -${ZSH_SPELLINE_CONTEXT_LINES} 2>/dev/null \
    | sed -e 's/\x1b\[[0-9;]*[a-zA-Z]//g' -e '/^[[:space:]]*$/d' \
    | tail -n ${ZSH_SPELLINE_CONTEXT_LINES} \
    | tail -c $(( ZSH_SPELLINE_CONTEXT_LINES * 200 ))
}

# ── prompt builder ────────────────────────────────────────────────────────────
# Default prompt function. Receives a single argument: the user request.
# Override via ZSH_SPELLINE_PROMPT_FUNC to customize.
_spelline_build_prompt() {
  local request="$1"
  local git_info=$(_spelline_git_info)
  local hist=$(_spelline_history)
  local context=$(_spelline_tmux_context)
  local uname_info=$(uname -a 2>/dev/null)
  cat <<EOF
You are a shell command generator. Output ONLY the shell command — no explanation, no markdown fences, no single backticks, no comments.

Context:
- Shell: zsh ${ZSH_VERSION}
${uname_info:+- System: ${uname_info}}
- CWD: ${PWD}
${git_info:+- ${git_info}}
${hist:+- Recent history (for reference only; commands listed may have failed):
\`\`\`
${hist}
\`\`\`}
${context:+
- Terminal output (last ${ZSH_SPELLINE_CONTEXT_LINES} lines):
\`\`\`
${context}
\`\`\`}

User request: ${request}

Output rules:
- If the request is straightforward, output exactly 1 command.
- If the user asks for alternatives or multiple options, output up to ${ZSH_SPELLINE_MAX_CANDIDATES} candidates, ordered by relevance (best match first).
- Separate each candidate with a line containing ONLY '---' (on its own line, with a newline before and after).
- A command may span multiple lines.
- If you cannot generate a valid command, output the user request as-is.
- No numbering, no explanation, no markdown fences.

Example output for a single command:
find . -type f -name "*.log"

Example output for multiple candidates:
find . -type f -name "*.log"
---
ls -la *.log
---
for f in *.log; do
  echo "\$f: \$(wc -l < "\$f") lines"
done
EOF
}

# ── core widget ───────────────────────────────────────────────────────────────
_spelline_generate() {
  setopt LOCAL_OPTIONS NO_NOTIFY NO_MONITOR
  local user_input="$BUFFER"
  [[ -z "$user_input" ]] && return

  if [[ -z "$ZSH_SPELLINE_CMD" ]]; then
    zle -M "[zsh-spelline] ZSH_SPELLINE_CMD (LLM backend) is not set. See https://github.com/wateret/zsh-spelline#install"
    return
  fi

  # ── build prompt ───────────────────────────────────────────────────────────
  local _prompt
  _prompt=$("$ZSH_SPELLINE_PROMPT_FUNC" "$user_input")

  # ── save to history ──────────────────────────────────────────────────────
  if [[ -n "$ZSH_SPELLINE_HISTORY_FILE" ]]; then
    print -r -- "$user_input" >> "$ZSH_SPELLINE_HISTORY_FILE"
  fi

  # ── log prompt ────────────────────────────────────────────────────────────
  if [[ -n "$ZSH_SPELLINE_LOG_DIR" ]]; then
    mkdir -p "$ZSH_SPELLINE_LOG_DIR" 2>/dev/null
    local logfile="${ZSH_SPELLINE_LOG_DIR}/${$}_$(date +%Y%m%d_%H%M%S)_${${EPOCHREALTIME#*.}[1,3]}.log"
    cat > "$logfile" <<LOGEOF
# Config

\`\`\`
ZSH_SPELLINE_CMD=${ZSH_SPELLINE_CMD}
ZSH_SPELLINE_CONTEXT_LINES=${ZSH_SPELLINE_CONTEXT_LINES}
ZSH_SPELLINE_HISTORY_LINES=${ZSH_SPELLINE_HISTORY_LINES}
ZSH_SPELLINE_MAX_CANDIDATES=${ZSH_SPELLINE_MAX_CANDIDATES}
ZSH_SPELLINE_SPINNER=${ZSH_SPELLINE_SPINNER}
ZSH_SPELLINE_SPINNER_COLOR=${ZSH_SPELLINE_SPINNER_COLOR}
ZSH_SPELLINE_VERBOSE_AFTER=${ZSH_SPELLINE_VERBOSE_AFTER}
ZSH_SPELLINE_KEYBINDING=${ZSH_SPELLINE_KEYBINDING}
ZSH_SPELLINE_PROMPT_FUNC=${ZSH_SPELLINE_PROMPT_FUNC}
\`\`\`

# Prompt

${_prompt}
LOGEOF
  fi

  # ── show spinner while waiting ─────────────────────────────────────────────
  local saved_buffer="$BUFFER"
  local saved_cursor="$CURSOR"
  POSTDISPLAY=""

  # ── call LLM CLI ───────────────────────────────────────────────────────────
  local result exit_code _cancelled=0
  local start_time=$EPOCHREALTIME
  local _tmpdir="${TMPDIR:-/tmp}"
  local _tmpfile="${_tmpdir}/spelline_$$"
  local _errfile="${_tmpdir}/spelline_err_$$"
  local _infile="${_tmpdir}/spelline_in_$$"
  printf '%s' "$_prompt" > "$_infile"

  ${=ZSH_SPELLINE_CMD} < "$_infile" > "$_tmpfile" 2>"$_errfile" &
  local _pid=$!
  trap "_cancelled=1; kill $_pid 2>/dev/null; wait $_pid 2>/dev/null" INT

  # animate spinner while waiting
  local _spin_chars
  case "$ZSH_SPELLINE_SPINNER" in
    braille) _spin_chars=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏') ;;
    *)       _spin_chars=('/' '-' '\' '|') ;;
  esac
  local _n=${#_spin_chars[@]}
  local _anim_colors=(39 38 44 43 49 48 84 83 119 118 154 153 189 188 183 182 177 176 171 170 135 134 99 98 63 62)
  local _nc=${#_anim_colors[@]}
  local _llm_name=${ZSH_SPELLINE_CMD%% *}
  (( ${#_llm_name} == 0 || ${#_llm_name} > 32 )) && _llm_name="LLM"
  local _pstart=${#BUFFER}
  local _spin_i=0
  while kill -0 $_pid 2>/dev/null; do
    local _sc=${_spin_chars[$(( _spin_i % _n + 1 ))]}
    local _msg="${_sc} Asking ${_llm_name}"
    if (( ZSH_SPELLINE_VERBOSE_AFTER > 0 )) && (( EPOCHREALTIME - start_time >= ZSH_SPELLINE_VERBOSE_AFTER )); then
      _msg+=" (^C or ESC to cancel) $(printf '%4.1f' $(( EPOCHREALTIME - start_time )))s"
    fi
    POSTDISPLAY=$'\n'"${_msg}"
    local _pend=$(( _pstart + ${#POSTDISPLAY} ))
    case "$ZSH_SPELLINE_SPINNER_COLOR" in
      animated) region_highlight=("${_pstart} ${_pend} fg=${_anim_colors[$(( _spin_i % _nc + 1 ))]}") ;;
      plain)    region_highlight=("${_pstart} ${_pend} fg=default") ;;
      *)        region_highlight=("${_pstart} ${_pend} fg=${ZSH_SPELLINE_SPINNER_COLOR}") ;;
    esac
    zle -R
    _spin_i=$(( _spin_i + 1 ))
    # check for ESC key; read -t also serves as the spinner delay
    local _key=""
    if read -r -k 1 -t 0.1 _key 2>/dev/null; then
      if [[ "$_key" == $'\e' ]]; then
        _cancelled=1; kill $_pid 2>/dev/null; wait $_pid 2>/dev/null
        break
      fi
    fi
  done

  wait $_pid 2>/dev/null
  exit_code=$?
  trap - INT
  rm -f "$_infile"

  if (( _cancelled )); then
    rm -f "$_tmpfile" "$_errfile"
    BUFFER="$saved_buffer"; CURSOR=$saved_cursor; POSTDISPLAY=""; zle redisplay; return
  fi
  result=$(<"$_tmpfile")
  local _stderr=$(<"$_errfile" 2>/dev/null)
  rm -f "$_tmpfile" "$_errfile"

  local elapsed=$(( EPOCHREALTIME - start_time ))

  # ── log result ───────────────────────────────────────────────────────────
  if [[ -n "$ZSH_SPELLINE_LOG_DIR" ]] && [[ -n "$logfile" ]]; then
    printf '\n# Result\n\n- elapsed: %.2fs\n- exit: %d\n' "$elapsed" "$exit_code" >> "$logfile"
    printf '\n## stdout\n\n%s\n' "$result" >> "$logfile"
    [[ -n "$_stderr" ]] && printf '\n## stderr\n\n%s\n' "$_stderr" >> "$logfile"
  fi

  # ── parse result ───────────────────────────────────────────────────────────
  if [[ $exit_code -eq 0 ]] && [[ -n "$result" ]]; then
    _spelline_parse_result "$result"
    local -a candidates=("${_spelline_candidates[@]}")

    local selected
    if (( ${#candidates[@]} > 1 )) && (( $+commands[fzf] )); then
      # join candidates with null byte for fzf --read0
      selected=$(printf '%s\0' "${candidates[@]}" \
        | fzf --read0 --height=~${ZSH_SPELLINE_MAX_CANDIDATES} --reverse --no-sort --prompt="cmd> ")
    else
      selected="${candidates[1]}"
    fi

    if [[ -n "$selected" ]]; then
      BUFFER="$selected"
      CURSOR=${#BUFFER}
    else
      BUFFER="$saved_buffer"
      CURSOR=$saved_cursor
    fi
  else
    BUFFER="$saved_buffer"
    CURSOR=$saved_cursor
    local _errmsg="[zsh-spelline] ✗ failed (exit=$exit_code)"
    [[ -n "$_stderr" ]] && _errmsg+=": ${${_stderr%%$'\n'*}[1,100]}"
    POSTDISPLAY=$'\n'"${_errmsg}"
    region_highlight=("${_pstart} $(( _pstart + ${#POSTDISPLAY} )) fg=red")
    zle -R
    local _deadline=$(( EPOCHREALTIME + 10 ))
    while (( EPOCHREALTIME < _deadline )); do
      if read -k 1 -t 0 2>/dev/null; then
        break
      fi
      sleep 0.1 &
      wait $! 2>/dev/null
    done
  fi

  POSTDISPLAY=""
  zle redisplay
}

zle -N _spelline_generate
if [[ -n "$ZSH_SPELLINE_KEYBINDING" ]]; then
  bindkey "$ZSH_SPELLINE_KEYBINDING" _spelline_generate
fi

# ── history search widget ────────────────────────────────────────────────────
_spelline_history_search() {
  [[ ! -r "$ZSH_SPELLINE_HISTORY_FILE" ]] && return
  if (( ! $+commands[fzf] )); then
    zle -M "[zsh-spelline] fzf is required for history search"
    return
  fi
  local selected
  if command -v tac &>/dev/null; then
    selected=$(tac "$ZSH_SPELLINE_HISTORY_FILE" | awk '!seen[$0]++' \
      | fzf --height=~20 --no-sort --prompt="spelline> " --scheme=history)
  else
    selected=$(tail -r "$ZSH_SPELLINE_HISTORY_FILE" | awk '!seen[$0]++' \
      | fzf --height=~20 --no-sort --prompt="spelline> " --scheme=history)
  fi
  if [[ -n "$selected" ]]; then
    BUFFER="$selected"
    CURSOR=${#BUFFER}
  fi
  zle redisplay
}

zle -N _spelline_history_search
if [[ -n "$ZSH_SPELLINE_HISTORY_KEYBINDING" ]]; then
  bindkey "$ZSH_SPELLINE_HISTORY_KEYBINDING" _spelline_history_search
fi
